const BACKEND_URL = "http://127.0.0.1:8000";

/**
 * [HYBRID SYNC IDENTITY HANDLER]
 * Receives the cryptographically secure ID token string generated by the Firebase 
 * Frontend SDK and dispatches it to FastAPI to open a parallel tracking row in PostgreSQL.
 */
export async function syncFirebaseSignupWithBackend(payload: {
  idToken: string;
  fullName: string;
  roleSelection: string; // Must match standard server enum strings: "student" or "teacher"
}) {
  const response = await fetch(`${BACKEND_URL}/auth/verify-sync-signup`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      idToken: payload.idToken,
      fullName: payload.fullName,
      roleSelection: payload.roleSelection,
    }),
  });

  if (!response.ok) {
    const errorDetails = await response.json();
    throw new Error(errorDetails.detail || "Federated identity signup synchronization failed.");
  }
  return response.json();
}

/**
 * Validates active Firebase sessions with our local Python server before unlocking dashboards.
 */
export async function syncFirebaseLoginWithBackend(idToken: string) {
  const response = await fetch(`${BACKEND_URL}/auth/verify-sync-login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ idToken }),
  });

  if (!response.ok) {
    const errorDetails = await response.json();
    throw new Error(errorDetails.detail || "Federated identity login synchronization failed.");
  }
  return response.json();
}

/**
 * Hands text materials down to the RAG document ingestion backend router.
 */
export async function uploadStudyMaterial(textContext: string, firebaseToken: string) {
  const response = await fetch(`${BACKEND_URL}/documents/upload`, {
    method: "POST",
    headers: { 
      "Content-Type": "application/json",
      // Include the token string inside the Auth schema header to pass FastAPI dependency checks
      "Authorization": `Bearer ${firebaseToken}` 
    },
    body: JSON.stringify({ title: "Lesson Context Notes", textBody: textContext }),
  });
  
  if (!response.ok) throw new Error("Document processing loop broken.");
  return response.json();
}
